### PR TITLE
Pbs to slurm

### LINKED ISSUE #14: Change pbs scripts to slurm

### PR DESCRIPTION
**Pull request by wclose**
This was supposed to fix #14 but it looks like it's already been done. Do with it what you will.

### CODE REVIEW

**Comment by BTopcuoglu** [comment]
You can do these changes in lab meeting if you prefer:)

**Comment by BTopcuoglu** [comment]
Can you check if it runs in the cluster?

**Comment by wclose** [comment]
This won't run on GL using modules because some of the packages are missing. Will need to create a conda env and activate it before running on a cluster. See #37 for status

**Comment by BTopcuoglu** [comment]
Good idea @wclose! Conda env for the packages will be a good utility for people to use on any HPC or locally as well. 

I'll also add some documentation on how to install libraries in the Great Lakes cluster to the home directory in case people don't want to use conda at the moment.

**Pull request merged**
